// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cartFieldNames          = builder.RawFieldNames(&Cart{})
	cartRows                = strings.Join(cartFieldNames, ",")
	cartRowsExpectAutoSet   = strings.Join(stringx.Remove(cartFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cartRowsWithPlaceHolder = strings.Join(stringx.Remove(cartFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	cartModel interface {
		Insert(ctx context.Context, data *Cart) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Cart, error)
		Update(ctx context.Context, data *Cart) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCartModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Cart struct {
		Id         int64     `db:"id"`          // 购物车id
		Userid     int64     `db:"userid"`      // 用户id
		Proid      int64     `db:"proid"`       // 商品id
		Quantity   int64     `db:"quantity"`    // 数量
		Checked    int64     `db:"checked"`     // 是否选择,1=已勾选,0=未勾选
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newCartModel(conn sqlx.SqlConn) *defaultCartModel {
	return &defaultCartModel{
		conn:  conn,
		table: "`cart`",
	}
}

func (m *defaultCartModel) withSession(session sqlx.Session) *defaultCartModel {
	return &defaultCartModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`cart`",
	}
}

func (m *defaultCartModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCartModel) FindOne(ctx context.Context, id int64) (*Cart, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cartRows, m.table)
	var resp Cart
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCartModel) Insert(ctx context.Context, data *Cart) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, cartRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Userid, data.Proid, data.Quantity, data.Checked)
	return ret, err
}

func (m *defaultCartModel) Update(ctx context.Context, data *Cart) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cartRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Userid, data.Proid, data.Quantity, data.Checked, data.Id)
	return err
}

func (m *defaultCartModel) tableName() string {
	return m.table
}
