// Code generated by goctl. DO NOT EDIT.
package types

type RecommondRequest struct {
	Cursor int64 `json:"cursor"` // 游标
	Ps     int64 `json:"ps"`     // 每页数量`
}

type RecommondResponse struct {
	Products      []*Product `json:"products"`       // 商品列表
	IsEnd         bool       `json:"is_end"`         // 是否结束
	RecommondTime int64      `json:"recommond_time"` // 推荐时间
}

type Product struct {
	ID          int64   `json:"id"`          // 商品ID
	Name        string  `json:"name"`        // 产品名称
	Description string  `json:"description"` // 商品描述
	Price       float64 `json:"price"`       // 商品价格
	Stock       int64   `json:"stock"`       // 库存
	Category    string  `json:"category"`    // 分类
	Status      int64   `json:"status"`      // 状态：1-正常，2-下架
	CreateTime  int64   `json:"create_time"` // 创建时间
	UpdateTime  int64   `json:"update_time"` // 更新时间
}

type FlashSaleResponse struct {
	StartTime int64      `json:"start_time"`
	Products  []*Product `json:"products"`
}

type BannerResponse struct {
	Products []*Product `json:"products"`
}

type CategoryListRequest struct {
	Cursor   int64  `json:"cursor"`   // 游标
	Ps       int64  `json:"ps"`       // 每页数量
	Category string `json:"category"` //分类
	Sort     string `json:"sort"`     //排序
}

type CategoryListResponse struct {
	Products []*Product `json:"products"`
	IsEnd    int64      `json:"is_end"`
	LastVal  string     `json:"last_val"`
}

type CartListRequest struct {
	UID int64 `json:"uid"` // 用户ID
}

type CartListResponse struct {
	Products []*CartProduct `json:"products"`
}

type CartProduct struct {
	Product *Product `json:"product"`
	Count   int64    `json:"count"`
}

type ProductCommentRequest struct {
	ProductID int64 `json:"product_id"` // 商品ID
	Cursor    int64 `json:"cursor"`     // 游标
	Ps        int64 `json:"ps"`         // 每页数量
}

type ProductCommentResponse struct {
	Comments    []*Comment `json:"comments"`
	IsEnd       int64      `json:"is_end"`
	CommentTime int64      `json:"comment_time"`
}

type Comment struct {
	ID         int64    `json:"id"`
	ProductID  int64    `json:"product_id"`
	Content    string   `json:"content"`
	Images     []*Image `json:"images"`
	User       *User    `json:"user"`
	CreateTime int64    `json:"create_time"`
	UpdateTime int64    `json:"update_time"`
}

type User struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
}

type Image struct {
	ID  int64  `json:"id"`
	URL string `json:"url"`
}
