// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shoppingFieldNames          = builder.RawFieldNames(&Shopping{})
	shoppingRows                = strings.Join(shoppingFieldNames, ",")
	shoppingRowsExpectAutoSet   = strings.Join(stringx.Remove(shoppingFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shoppingRowsWithPlaceHolder = strings.Join(stringx.Remove(shoppingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shoppingModel interface {
		Insert(ctx context.Context, data *Shopping) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Shopping, error)
		Update(ctx context.Context, data *Shopping) error
		Delete(ctx context.Context, id int64) error
	}

	defaultShoppingModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Shopping struct {
		Id               int64     `db:"id"`                // 收货信息表id
		Orderid          string    `db:"orderid"`           // 订单id
		Userid           int64     `db:"userid"`            // 用户id
		ReceiverName     string    `db:"receiver_name"`     // 收货姓名
		ReceiverPhone    string    `db:"receiver_phone"`    // 收货固定电话
		ReceiverMobile   string    `db:"receiver_mobile"`   // 收货移动电话
		ReceiverProvince string    `db:"receiver_province"` // 省份
		ReceiverCity     string    `db:"receiver_city"`     // 城市
		ReceiverDistrict string    `db:"receiver_district"` // 区/县
		ReceiverAddress  string    `db:"receiver_address"`  // 详细地址
		CreateTime       time.Time `db:"create_time"`       // 创建时间
		UpdateTime       time.Time `db:"update_time"`       // 更新时间
	}
)

func newShoppingModel(conn sqlx.SqlConn) *defaultShoppingModel {
	return &defaultShoppingModel{
		conn:  conn,
		table: "`shopping`",
	}
}

func (m *defaultShoppingModel) withSession(session sqlx.Session) *defaultShoppingModel {
	return &defaultShoppingModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`shopping`",
	}
}

func (m *defaultShoppingModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShoppingModel) FindOne(ctx context.Context, id int64) (*Shopping, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shoppingRows, m.table)
	var resp Shopping
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShoppingModel) Insert(ctx context.Context, data *Shopping) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, shoppingRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Orderid, data.Userid, data.ReceiverName, data.ReceiverPhone, data.ReceiverMobile, data.ReceiverProvince, data.ReceiverCity, data.ReceiverDistrict, data.ReceiverAddress)
	return ret, err
}

func (m *defaultShoppingModel) Update(ctx context.Context, data *Shopping) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shoppingRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Orderid, data.Userid, data.ReceiverName, data.ReceiverPhone, data.ReceiverMobile, data.ReceiverProvince, data.ReceiverCity, data.ReceiverDistrict, data.ReceiverAddress, data.Id)
	return err
}

func (m *defaultShoppingModel) tableName() string {
	return m.table
}
